//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Reflection;

[assembly: System.Reflection.AssemblyCompanyAttribute("CodeShayk")]
[assembly: System.Reflection.AssemblyConfigurationAttribute("Release")]
[assembly: System.Reflection.AssemblyCopyrightAttribute("2026")]
[assembly: System.Reflection.AssemblyDescriptionAttribute(".Net Library to implement transactional events in domain model.")]
[assembly: System.Reflection.AssemblyFileVersionAttribute("4.1.0")]
[assembly: System.Reflection.AssemblyInformationalVersionAttribute("4.1.0")]
[assembly: System.Reflection.AssemblyProductAttribute("Dormito")]
[assembly: System.Reflection.AssemblyTitleAttribute("DomainEvents")]
[assembly: System.Reflection.AssemblyVersionAttribute("4.1.0")]
[assembly: System.Reflection.AssemblyMetadataAttribute("RepositoryUrl", "https://github.com/Codeshayk/DomainEvents")]

// Generated by the MSBuild WriteCodeFragment class.

