//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Reflection;

[assembly: System.Reflection.AssemblyCompanyAttribute("Tech Ninja Labs")]
[assembly: System.Reflection.AssemblyConfigurationAttribute("Release")]
[assembly: System.Reflection.AssemblyCopyrightAttribute("2024")]
[assembly: System.Reflection.AssemblyDescriptionAttribute(".Net Library to implement transactional events in domain model.")]
[assembly: System.Reflection.AssemblyFileVersionAttribute("3.0.1.0")]
[assembly: System.Reflection.AssemblyInformationalVersionAttribute("3.0.1")]
[assembly: System.Reflection.AssemblyProductAttribute("Dormito")]
[assembly: System.Reflection.AssemblyTitleAttribute("Dormito.DomainEvents")]
[assembly: System.Reflection.AssemblyVersionAttribute("3.0.1.0")]
[assembly: System.Reflection.AssemblyMetadataAttribute("RepositoryUrl", "https://github.com/TechNinjaLabs/Ninja.DomainEvents")]

// Generated by the MSBuild WriteCodeFragment class.

