# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET

on:
  create:
    branches: 
      - release/**
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master", "pre-release" ]
jobs:
  build:
  
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.GH_Packages }}
      GITHUB_USERNAME: ${{ github.actor }}
      working-directory: /home/runner/work/DomainEvents/DomainEvents
    steps:
    - name: Install GitVersion
      uses: gittools/actions/gitversion/setup@v0.9.7
      with:
          versionSpec: '5.x'
    - name: Check out Code 
      uses: actions/checkout@v2
      with:
          fetch-depth: 0
    - name: Determine Version
      id: gitversion
      uses: gittools/actions/gitversion/execute@v0.9.7
    - name: Restore dependencies
      run: dotnet restore         
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 6.0.x
    - name: Restore dependencies
      run: dotnet restore
      working-directory: ${{ env.working-directory }}
    - name: Build
      run: dotnet build --no-restore
      working-directory: ${{ env.working-directory }}
    - name: Test
      run: dotnet test --no-build --verbosity normal
      working-directory: ${{ env.working-directory }}
    - name: Install gpr
      run: dotnet tool install gpr --global
    - name: gpr upload
      run: find -name "*.nupkg" -print -exec gpr push -k ${{env.GITHUB_TOKEN}} {} \;
    - name: Publish to Nuget
      if: startsWith(github.ref, 'refs/heads/release')
      run: dotnet nuget push ${{env.working-directory}}/DomainEvents/bin/Release/*.nupkg --skip-duplicate --api-key ${{ secrets.NUGET_API_KEY }} --source https://api.nuget.org/v3/index.json